name: Build
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running this workflow'
        required: false
        default: 'Manual test'

jobs:
  linux_plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: 2.1.0-beta3--3.4.0
          command: luajit -v
  mac_plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: 2.1.0-beta3--3.4.0
          command: luajit -v
        env:
          CMAKE_BUILD_TYPE: Release
          MACOSX_DEPLOYMENT_TARGET: 10.15
          DEPS_CMAKE_FLAGS: -DCMAKE_CXX_COMPILER=$(xcrun -find c++)
